name: Build Package

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package with twine
      run: |
        twine check dist/*
    
    - name: List package contents
      run: |
        echo "Built packages:"
        ls -la dist/
        echo ""
        echo "Package info:"
        pip show --verbose dist/*.whl || true
    
    - name: Test installation
      run: |
        pip install dist/*.whl
        python -c "import revoxx; print(f'Revoxx version: {revoxx.__version__}')"
        revoxx --help || true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
        retention-days: 7